const clouds = ["Agreements and Contracts", "Content Publishing","Education","Human Resources", "Financial"];

// Important: lastUpdated date should be unique to ensure stable sort across browsers
const products = [
  {
    id: 0,
    name: "Agreement",
    description: "Adobe Creative Cloud APIs and SDKs enable developers",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/agreement.jpg",
    discover: "https://www.adobe.com/go/dcdg_sampleagreement",
    docs: false,
    lastUpdated: "2020",
    cloud: clouds[0],
  },
  {
    id: 1,
    name: "Grant application",
    description:
      "The Libraries API lets you connect your app to Creative Cloud and expand the reach of your users' creative systems.",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/grant_application.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplegrant",
    docs: false,
    lastUpdated: "2019",
    cloud: clouds[4],
  },
  {
    id: 2,
    name: "Invoice",
    description:
      "Adobe XD’s powerful API platform lets developers and users extend XD within the app, or in the cloud.",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/invoice.jpg",
    discover: "https://www.adobe.com/go/dcdg_sampleinvoice",
    docs: false,
    lastUpdated: "2017",
    cloud: clouds[4],
  },
  {
    id: 3,
    name: "Sample proposal",
    description: "Give your users access to the perfect Adobe Stock",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/proposal_letter.jpg",
    discover: "https://www.adobe.com/go/dcdg_sampleproposal",
    docs: false,
    lastUpdated: "2002",
    cloud: clouds[4],
  },
  {
    id: 4,
    name: "Certification report",
    description:
      "With Photoshop APIs and SDKs, build plugins and integrations that harness the power of the world's best image editing",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/offer_letter.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },

  {
    id: 5,
    name: "Offer Letter",
    description: "Create effects, define presets and brushes, manipu",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/offer_letter.jpg",
    discover: "https://www.adobe.com/go/dcdg_sampleofferletter",
    docs: false,
    lastUpdated: "1999",
    cloud: clouds[0],
  },
  {
    id: 6,
    name: "Sample Award Letter",
    description: "Create effects, define presets and brushes, manipu",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/lms_report.jpg",
    discover: "https://www.adobe.com/go/dcdg_sampleawardletter",
    docs: false,
    lastUpdated: "1999",
    cloud: clouds[1],
  },
  {
    id: 7,
    name: "City Programs Sheet",
    description: "Create effects, define presets and brushes, manipu",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/lms_report.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplecityprogramsheet",
    docs: false,
    lastUpdated: "1999",
    cloud: clouds[1],
  },
  {
    id: 8,
    name: "LMS Certificate",
    description:"LMS Certificate",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/lms_certificate.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 9,
    name: "Sample Annual Report",
    description:"Sample Annual Report",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/annual_report.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 10,
    name: "Employee Handbook",
    description:"Sample Annual Report",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/employee_handbook.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 10,
    name: "Remote Work",
    description:"Sample Annual Report",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/employee_remote.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 11,
    name: "Marketing Data Sheet",
    description:"Marketing Data Sheet",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/marketing_sheet.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 12,
    name: "Project Status Report",
    description:"Project Status Report",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/marketing_sheet.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 12,
    name: "Welcome Kit",
    description:"Welcome Kit",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/welcome_kit.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 13,
    name: "Receipt",
    description:"Receipt",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/service_receipt.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[4],
  },
  {
    id: 14,
    name: "Sales Order",
    description:"Sales Order",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/sales_order.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[4],
  },
  {
    id: 15,
    name: "Investment Proposal Letter",
    description:"Investment Proposal Letter",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/sales_order.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[4],
  },
  {
    id: 16,
    name: "Mortgage Proposal",
    description:"Investment Proposal Letter",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/mortgage_proposal.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[4],
  },
  {
    id: 17,
    name: "Purchase Order",
    description:"Investment Proposal Letter",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/purchase_order.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[4],
  },
  {
    id: 18,
    name: "Affidavit of Identity",
    description:"Affidavit of Identity",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/affidavit-of-identity.jpg",
    discover: "https://adobe.com/go/dcdg_sampleaffidavitofidentity",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 19,
    name: "Child Support",
    description:"Child Support",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/child-support-agreement.jpg",
    discover: "https://adobe.com/go/dcdg_samplechildsupport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 20,
    name: "Clinical Trial",
    description:"Clinical Trial",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/clinical-trial-consent.jpg",
    discover: "https://adobe.com/go/dcdg_sampleclinicaltrial",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 21,
    name: "Consulting Agreement",
    description:"Consulting Agreement",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/consulting-agreement.jpg",
    discover: "https://adobe.com/go/dcdg_sampleconsultingagreement",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 22,
    name: "Liability Consent Form",
    description:"Liability Consent Form",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/welcome_kit.jpg",
    discover: "https://adobe.com/go/dcdg_sampleliabilityconsentform",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 23,
    name: "Liability Release Form",
    description:"Liability Release Form",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/liability-release.jpg",
    discover: "https://adobe.com/go/dcdg_sampleliabilityreleaseform",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 24,
    name: "License Agreement",
    description:"License Agreement",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/licensing-agreeemnt.jpg",
    discover: "https://adobe.com/go/dcdg_samplelicenseagreement",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 25,
    name: "Living Trust",
    description:"Living Trust",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/living-trust.jpg",
    discover: "https://adobe.com/go/dcdg_samplelivingtrust",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 26,
    name: "Loan Agreement",
    description:"Loan Agreement",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/loan-agreement.jpg",
    discover: "https://adobe.com/go/dcdg_sampleloanagreement",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 27,
    name: "Non-Disclosure Agreements",
    description:"Non-Disclosure Agreements",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/nda.jpg",
    discover: "https://adobe.com/go/dcdg_samplenda",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 28,
    name: "Partnership Agreement",
    description:"Partnership Agreement",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/partnership-agreement.jpg",
    discover: "https://adobe.com/go/dcdg_samplepartnershipagreement",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 29,
    name: "Rental Agreement",
    description:"Rental Agreement",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/rental-agreement.jpg",
    discover: "https://adobe.com/go/dcdg_samplerentalagreement",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 30,
    name: "Terms and Conditions",
    description:"Terms and Conditions",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/terms-conditions.jpg",
    discover: "https://adobe.com/go/dcdg_sampletermsnconditions",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 31,
    name: "Catering Invoice",
    description:"Catering Invoice",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/catering-invocie.jpg",
    discover: "https://adobe.com/go/dcdg_samplecateringinvoice",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 32,
    name: "Credit Memo",
    description:"Terms and Conditions",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/credit-memo.jpg",
    discover: "https://adobe.com/go/dcdg_samplecreditmemo",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 33,
    name: "Executive Summary",
    description:"Executive Summary",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/executive-summary.jpg",
    discover: "https://adobe.com/go/dcdg_sampleexecutivesummary",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 34,
    name: "Press Release",
    description:"Press Release",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/press-release.jpg",
    discover: "https://adobe.com/go/dcdg_samplepressrelease",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 35,
    name: "Restaurant Menu",
    description:"Restaurant Menu",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/restaurant-menu.jpg",
    discover: "https://adobe.com/go/dcdg_samplerestaurantmenu",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 36,
    name: "White Paper",
    description:"White Paper",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/white-paper.jpg",
    discover: "https://adobe.com/go/dcdg_samplewhitepaper",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[1],
  },
  {
    id: 37,
    name: "Add/Drop Audit Form",
    description:"Add/Drop Audit Form",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/add-drop-audit-form.jpg",
    discover: "https://adobe.com/go/dcdg_sampleaddropform",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[2],
  },
  {
    id: 38,
    name: "Attendance Sheet",
    description:"Attendance Sheet",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/attendance-sheet.jpg",
    discover: "https://adobe.com/go/dcdg_sampleattendancesheet",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[2],
  },
  {
    id: 39,
    name: "High School Catalog",
    description:"High School Catalog",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/high-school-catalog.jpg",
    discover: "https://adobe.com/go/dcdg_samplehighschoolcatalog",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[2],
  },
  {
    id: 40,
    name: "Student Submission",
    description:"Student Submission",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/student-submission.jpg",
    discover: "https://adobe.com/go/dcdg_samplestudentsubmission",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[2],
  },
  {
    id: 41,
    name: "Change of Beneficiary",
    description:"Change of Beneficiary",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/change-of-benificiary.jpg",
    discover: "https://adobe.com/go/dcdg_samplechangebeneficiary",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[3],
  },
  {
    id: 42,
    name: "Salary Verification",
    description:"Salary Verification",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/salary-verification-letter.jpg",
    discover: "https://adobe.com/go/dcdg_samplesalaryverification",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[3],
  },
  {
    id: 43,
    name: "Standard Operation Procedure",
    description:"Standard Operation Procedure",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/sop.jpg",
    discover: "https://adobe.com/go/dcdg_samplestandardoperationprocedure",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[3],
  },
  {
    id: 44,
    name: "Travel Consent Form",
    description:"Travel Consent Form",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/travel-consent-form.jpg",
    discover: "https://adobe.com/go/dcdg_sampletravelconsentform",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[3],
  },
  {
    id: 45,
    name: "Eligibility of Sale",
    description:"Eligibility of Sale",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/agreement.jpg",
    discover: "https://adobe.com/go/dcdg_samplebillofsale",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[4],
  },
  {
    id: 46,
    name: "Service Receipt",
    description:"Service Receipt",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/service_receipt.jpg",
    discover: "https://adobe.com/go/dcdg_sampleservicereceipt",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[4],
  },
  {
    id: 47,
    name: "Shipping Notice",
    description:"Shipping Notice",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/shipping-notice.jpg",
    discover: "https://adobe.com/go/dcdg_sampleshippingnotice",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[4],
  },
  {
    id: 48,
    name: "Stock Sale and Purchase",
    description:"Stock Sale and Purchase",
    icon: "https://chrisconverse.github.io/developers-stage.adobe.com/gh-assets/img/template-icons/stock-sale-purchase.jpg",
    discover: "https://adobe.com/go/dcdg_samplestocksaleandpurchase",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[4],
  }
];

const sampleProducts = [
  {
    id: 0,
    name: "Agreement",
    description: "Adobe Creative Cloud APIs and SDKs enable developers",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/agreement.jpg",
    discover: "https://www.adobe.com/go/dcdg_sampleagreement",
    docs: false,
    lastUpdated: "2020",
    cloud: clouds[0],
  },
  {
    id: 1,
    name: "Grant application",
    description:
      "The Libraries API lets you connect your app to Creative Cloud and expand the reach of your users' creative systems.",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/grant_application.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplegrant",
    docs: false,
    lastUpdated: "2019",
    cloud: clouds[4],
  },
  {
    id: 2,
    name: "Invoice",
    description:
      "Adobe XD’s powerful API platform lets developers and users extend XD within the app, or in the cloud.",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/invoice.jpg",
    discover: "https://www.adobe.com/go/dcdg_sampleinvoice",
    docs: false,
    lastUpdated: "2017",
    cloud: clouds[4],
  },
  {
    id: 3,
    name: "Sample proposal",
    description: "Give your users access to the perfect Adobe Stock",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/proposal_letter.jpg",
    discover: "https://www.adobe.com/go/dcdg_sampleproposal",
    docs: false,
    lastUpdated: "2002",
    cloud: clouds[4],
  },
  {
    id: 4,
    name: "Certification report",
    description:
      "With Photoshop APIs and SDKs, build plugins and integrations that harness the power of the world's best image editing",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/offer_letter.jpg",
    discover: "https://www.adobe.com/go/dcdg_samplereport",
    docs: false,
    lastUpdated: "2018",
    cloud: clouds[0],
  },
  {
    id: 5,
    name: "Offer Letter",
    description: "Create effects, define presets and brushes, manipu",
    icon: "https://www.adobe.io/gh-assets/img/template-icons/lms_report.jpg",
    discover: "https://www.adobe.com/go/dcdg_sampleofferletter",
    docs: false,
    lastUpdated: "1999",
    cloud: clouds[0],
  }
];

module.exports = {
  clouds,
  products,
  sampleProducts
};